# Generated by Django 6.0 on 2025-12-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techblog',
            name='slug',
        ),
    ]
